### ISSUE TITLE
Error in template in intro-mdp/netconf/get_interface_list.py

### ISSUE THREAD

**Issue by steve2359** [CiscoDevNet/dnav3-code#33]
intro-mdp/netconf/get_interface_list.py

Second last tag should be `</interfaces>` not `</interface>`.

    netconf_filter = """
    <filter>
      <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
        <interface></interface>
      </interface>
    </filter>"""

Corrected version:

    netconf_filter = """
    <filter>
      <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
        <interface></interface>
      </interfaces>
    </filter>"""

Stacktrace of the error:
```
python get_interface_list.py 
Opening NETCONF Connection to ios-xe-mgmt.cisco.com
Sending a <get-config> operation to the device.

Traceback (most recent call last):
  File "get_interface_list.py", line 65, in <module>
    netconf_reply = m.get_config(source = 'running', filter = netconf_filter)
  File "/Users/taylor13/Sites/dnav3-code/venv/lib/python3.7/site-packages/ncclient/manager.py", line 170, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/Users/taylor13/Sites/dnav3-code/venv/lib/python3.7/site-packages/ncclient/manager.py", line 240, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/Users/taylor13/Sites/dnav3-code/venv/lib/python3.7/site-packages/ncclient/operations/retrieve.py", line 129, in request
    node.append(util.build_filter(filter))
  File "/Users/taylor13/Sites/dnav3-code/venv/lib/python3.7/site-packages/ncclient/operations/util.py", line 61, in build_filter
    rep = validated_element(spec, ("filter", qualify("filter")))
  File "/Users/taylor13/Sites/dnav3-code/venv/lib/python3.7/site-packages/ncclient/xml_.py", line 131, in validated_element
    ele = to_ele(x)
  File "/Users/taylor13/Sites/dnav3-code/venv/lib/python3.7/site-packages/ncclient/xml_.py", line 111, in to_ele
    return x if etree.iselement(x) else etree.fromstring(x.encode('UTF-8'), parser=parser)
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1765, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1127, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 5
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: interfaces line 3 and interface, line 5, column 24
```
I submitted a pull request to fix this already.

**Comment by denapom11** [comment]
Merged
