### ISSUE TITLE
infro-dnac/cmd-run/show_command.py fails to execute with traceback. Failure to obtain 'taskId'

### ISSUE THREAD

**Issue by JoelRiglerIG** [CiscoDevNet/dnav3-code#71]
Traceback:
(venv) JRIGLER-M-G5SZ:intro-dnac jrigler$ ./cmd-run/show_command.py
Traceback (most recent call last):
  File "./cmd-run/show_command.py", line 112, in <module>
    results_fileId = execute_commands(token, deviceIdList, commandList)
  File "./cmd-run/show_command.py", line 47, in execute_commands
    task_result = post_and_wait(token,url, payload)
  File "./cmd-run/show_command.py", line 25, in post_and_wait
    taskid = response.json()['response']['taskId']
KeyError: 'response'
---
Associated code line (line 25):

    taskid = response.json()['response']['taskId']

when parsing response from '/v1/network-device-poller/cli/read-request'.

Possible format issue with 'deviceUuids' as doing parallel tasks in POSTMAN results in
HTTP 404 (Not Found).  

Code parses prior get_deviceList() response, so Uuid should be correct.

**Comment by robertcsapo** [comment]
@JoelRiglerIG seems like this was fixed in commit 276c8a75e8f7ab4b64b2102a1b64ad162dbf4411

```
/dne-dna-code/intro-dnac/04_Cmd_Runner# python cmd_runner.py 
hostname                 id                       
3504_WLC                 72dc1f0a-e4da-4ec3-a055-822416894dd5
AAA                      3dd27ed6-44f9-486d-abaf-a779781431a0
leaf2.abc.inc            5bc5b967-3f83-4195-891c-788f3e9048f3
spine1.abc.inc           2f0b7d3b-c9e1-491e-a584-f272b5403719
```
